<a href="https://colab.research.google.com/github/sarahmilleraws/DATA_SCIENCE-Codes/blob/main/Statistics_Assignment_2_2ipynb_adl%C4%B1_not_defterinin_kopyas%C4%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [41]:
import numpy as np 
import pandas as pd
from scipy import stats 

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [2]:
samples = np.random.normal(100, 15, size = 1000)
samples

array([ 75.7441873 ,  88.465137  ,  97.44619172,  86.63664425,
       121.98689347, 101.04053026,  81.43667284,  87.61340266,
        97.7441929 , 102.26905382,  73.56717056,  89.63156493,
        98.57178992,  95.40257079, 110.32182113, 103.36509971,
        89.84405743, 101.24826286, 102.25770546, 102.17824884,
        92.1171821 , 142.33710655,  85.06629181,  83.51551517,
       101.7156288 ,  77.79776233,  73.65391389, 107.20497639,
       120.44234621, 103.4169221 ,  90.79073946,  74.96096918,
       111.17693185,  93.9895039 , 102.75836942,  97.6393349 ,
       124.35345688, 103.14396979,  88.62593317,  95.76857812,
        91.77370946,  82.81593902, 133.90525473,  86.22633516,
       111.06567671,  97.60831126,  95.2217985 ,  96.0007468 ,
       115.9986621 ,  96.06217033, 113.52823582, 103.96901621,
       101.80445745,  96.4935576 ,  93.79217235,  96.34203145,
       118.86472631,  98.74627858, 105.44220873,  98.97514179,
        89.34126228, 126.85364515,  99.97132215,  96.43

Compute the **mean**, **median**, and **mode**

In [3]:
mean = np.mean(samples)
median = np.median(samples)
mode = stats.mode(samples)

In [4]:
mean

100.9945149180072

In [5]:
median

101.28526877605259

In [6]:
mode

ModeResult(mode=array([55.16435671]), count=array([1]))

Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [7]:
from scipy.stats import iqr

In [8]:
min = np.min(samples)
max = np.max(samples)
q1 = np.percentile(samples, 25)
q3 = np.percentile(samples, 75)
iqr = iqr(samples)

In [9]:
min

55.16435670846864

In [10]:
max

142.3371065543078

In [11]:
q1

91.04428106463496

In [13]:
q3

111.23772071251936

In [14]:
iqr

20.193439647884404

Compute the **variance** and **standard deviation**

In [15]:
variance = np.var(samples)
std_dev = np.std(samples)

In [16]:
variance

224.87165148920403

In [17]:
std_dev

14.995721106009007

Compute the **skewness** and **kurtosis**

In [18]:
skewness = stats.skew(samples)
kurtosis = stats.kurtosis(samples)

In [19]:
skewness

-0.05833312017620134

In [20]:
kurtosis

-0.06065745684147528

## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [ ]:
x =  np.arange(10, 20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [ ]:
y = np.array([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])
y

array([ 2,  1,  4,  5,  8, 12, 18, 25, 96, 48])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [ ]:
r =  np.corrcoef(x,y)

In [ ]:
r

array([[1.        , 0.75864029],
       [0.75864029, 1.        ]])

## Pandas Correlation Calculation

Run the code below

In [ ]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

In [ ]:
x

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64

In [ ]:
y

0     2
1     1
2     4
3     5
4     8
5    12
6    18
7    25
8    96
9    48
dtype: int64

Call the relevant method  to calculate Pearson's r correlation.

In [ ]:
r = scipy.stats.pearsonr(x,y)
r

(0.758640289091187, 0.010964341301680813)

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [ ]:
rho = scipy.stats.spearmanr(x,y)
rho

SpearmanrResult(correlation=0.9757575757575757, pvalue=1.4675461874042197e-06)

## Seaborn Dataset Tips

Import Seaborn Library

In [37]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [38]:
tips = sns.load_dataset("tips")

In [39]:
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [69]:
np.var(tips)

total_bill    78.928131
tip            1.906609
size           0.900883
dtype: float64

In [26]:
np.mean(tips)

total_bill    19.785943
tip            2.998279
size           2.569672
dtype: float64

In [27]:
np.std(tips)

total_bill    8.884151
tip           1.380800
size          0.949149
dtype: float64

In [28]:
np.sqrt(np.var(tips))

total_bill    8.884151
tip           1.380800
size          0.949149
dtype: float64

In [49]:
tips["total_bill"].mode()

0    13.42
dtype: float64

In [50]:
tips["total_bill"].median()

17.795

In [51]:
tips["total_bill"].mean()

19.785942622950824

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [73]:
import scipy.stats
import numpy as np
import pandas as pd

In [79]:
tips.corr()   #Pearson Correlation 

total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000

In [82]:
tips.corr(method="spearman")

total_bill       tip      size
total_bill    1.000000  0.678968  0.604791
tip           0.678968  1.000000  0.468268
size          0.604791  0.468268  1.000000

In [83]:
tips.corr(method="kendall")

total_bill       tip      size
total_bill    1.000000  0.517181  0.484342
tip           0.517181  1.000000  0.378185
size          0.484342  0.378185  1.000000