<a href="https://colab.research.google.com/github/sarahmilleraws/DATA_SCIENCE-Codes/blob/main/Statistics_Assignment_2_ipynb_adl%C4%B1_not_defterinin_kopyas%C4%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [ ]:
import numpy as np 
import pandas as pd
from scipy import stats 

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [ ]:
samples = np.random.normal(100, 15, size = 1000)
samples

array([102.59036001,  99.24431416, 102.99915129,  86.98112337,
       102.53645898,  82.96524388, 103.35742689,  94.32091623,
        95.41052246, 114.4836871 ,  98.24217896, 104.01829497,
       108.85826717,  93.25636143, 105.75196478,  82.55801282,
        91.15268905,  80.97161241, 112.2850869 , 108.16144014,
       111.27914061,  71.63024902,  84.86704678, 108.6622    ,
       107.3462169 ,  91.21861209,  77.41507315, 102.81967967,
       124.98004885,  91.25220471, 111.09858253,  88.03961915,
        77.91977558, 105.74094399, 108.45469547,  68.368964  ,
       112.48110496, 103.0942759 ,  98.81614354,  76.22983586,
        81.38660457, 114.0711039 ,  78.81216411,  77.07322703,
       112.65139666, 109.48809765,  96.25143166, 115.61298591,
        80.64365858,  82.14361966, 108.03082839,  98.32282132,
        93.86366521, 101.07344442,  86.89351203, 123.67182843,
        87.36187468, 102.66068541,  79.61815179,  76.70128956,
        83.1674921 ,  98.74232701, 126.25023258, 120.65

Compute the **mean**, **median**, and **mode**

In [ ]:
mean = np.mean(samples)
median = np.median(samples)
mode = stats.mode(samples)

In [ ]:
mean

100.01532226198431

In [ ]:
median

99.7251159780756

In [ ]:
mode

ModeResult(mode=array([48.44883304]), count=array([1]))

Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [ ]:
from scipy.stats import iqr

In [ ]:
min = np.min(samples)
max = np.max(samples)
q1 = np.percentile(samples, 25)
q3 = np.percentile(samples, 75)
iqr = iqr(samples)

In [ ]:
min

48.44883304098717

In [ ]:
max

150.4234744006846

In [ ]:
q1

89.47054300040364

In [ ]:
q3

110.01713390243955

In [ ]:
iqr

20.546590902035916

Compute the **variance** and **standard deviation**

In [ ]:
variance = np.var(samples)
std_dev = np.std(samples)

In [ ]:
variance

219.61593379705135

In [ ]:
std_dev

14.819444449676626

Compute the **skewness** and **kurtosis**

In [ ]:
skewness = stats.skew(samples)
kurtosis = stats.kurtosis(samples)

In [ ]:
skewness

0.1170137795987346

In [ ]:
kurtosis

0.03269114334263579

## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [ ]:
x =  np.arange(10, 20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [ ]:
y = np.array([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])
y

array([ 2,  1,  4,  5,  8, 12, 18, 25, 96, 48])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [ ]:
r =  np.corrcoef(x,y)

In [ ]:
r

array([[1.        , 0.75864029],
       [0.75864029, 1.        ]])

## Pandas Correlation Calculation

Run the code below

In [ ]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

In [ ]:
x

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64

In [ ]:
y

0     2
1     1
2     4
3     5
4     8
5    12
6    18
7    25
8    96
9    48
dtype: int64

Call the relevant method  to calculate Pearson's r correlation.

In [ ]:
r = scipy.stats.pearsonr(x,y)
r

(0.758640289091187, 0.010964341301680813)

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [ ]:
rho = scipy.stats.spearmanr(x,y)
rho

SpearmanrResult(correlation=0.9757575757575757, pvalue=1.4675461874042197e-06)

## Seaborn Dataset Tips

Import Seaborn Library

In [ ]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [ ]:
tips = sns.load_dataset("tips")

In [ ]:
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

Generate descriptive statistics include those that summarize the central tendency, dispersion

Call the relevant method to calculate pairwise Pearson's r correlation of columns